### ISSUE TITLE
suspected version checking error during gem install

### ISSUE THREAD

**Issue by mistergibson** [negativecode/vines#1]
OS: x86 Ubuntu, and PPC Debian -- same result

Ruby Version: ruby 1.9.2dev (2010-07-02) [i486-linux] & ruby 1.9.2dev (2010-07-11) [powerpc-linux]

Your installer does not accept my versions of Ruby, probably because of the 'dev' suffix.  Given the >grrr< slowness of the distro maintainers in keeping ruby updated in the package manager, I've had to resort to adding a ppa for ubuntu, and compiling from scratch on the PPC unit.

Given the hoops I have to jump through to get a nearly current version of ruby on my systems, I am appealing to you to accept my ruby version with a more flexible version of the version checking code, rather than having me running around attempting to rebuild it all on my systems.  They are, after all, valid 1.9.2 installations.

Thanks,

mistergibson

**Comment by dgraham** [comment]
We test and support Vines on the official 1.9.2 releases.  RVM is an easy way to get Ruby installed, no hoops required!  We've documented the steps here: http://www.getvines.com/ruby/.
