### ISSUE TITLE
 multi_json conflicts

### ISSUE THREAD

**Issue by paulhsu** [negativecode/vines#11]
when I run vines start -d, I get the following message

Unable to activate couchrest-1.1.2, because multi_json-1.2.0 conflicts with multi_json (~> 1.0.0)

**Comment by dgraham** [comment]
I'm not sure why that would happen because Vines uses em-http-request to talk to CouchDB, not couchrest.  Is the couchrest gem something you're loading into the chat server?

**Comment by dgraham** [comment]
I see what's happening now.  The vines-services gem loads couchrest which defines its dependency on multi_json ~> 1.0.0. The activesupport gem defines its dependency on multi_json ~> 1.0.  So if activesupport is installed first, we'll get multi_json 1.3.2 (the latest version) and 1.0.4 (the version couchrest needs).

I opened this pull request to update the couchrest dependency on multi_json:
https://github.com/couchrest/couchrest/pull/85

As a workaround, you can uninstall all versions of multi_json other than 1.0.4.
gem uninstall multi_json --version 1.2.0

**Comment by paulhsu** [comment]
I use the workaround to solve it.

Thanks.
