### ISSUE TITLE
Unable to convert UTF-8 to..... US-ASCII

### ISSUE THREAD

**Issue by zenwong** [negativecode/vines#12]
getting these errors when I install through gem:

unable to convert "\xF1" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for README, skipping
unable to convert "\xF1" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for README.rdoc, skipping
unable to convert "\xC3" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for TAGS, skipping

**Comment by dgraham** [comment]
Those are just documentation warnings from the builder gem. I always disable rdoc and ri documentation when installing gems because they take forever to run.  You can disable them by saying `gem install vines --no-rdoc --no-ri` or by adding this to your $HOME/.gemrc file

```
install: --no-rdoc --no-ri
update:  --no-rdoc --no-ri
```

**Comment by zenwong** [comment]
Ahh I see (ruby noob here)
