### ISSUE TITLE
Implement XEP-0060 (PubSub)

### ISSUE THREAD

**Issue by jpcaruana** [negativecode/vines#18]
Please consider implementing XEP-0060: Publish-Subscribe http://xmpp.org/extensions/xep-0060.html

**Comment by dgraham** [comment]
This was implemented along with [clustering](http://www.negativecode.com/posts/2012/01/30/vines-xmpp-server-now-with-clustering/) back in January.

**Comment by jpcaruana** [comment]
Great ! Sadly I couldn't find the information easily
Thanks.

**Comment by jpcaruana** [comment]
well, I found it : http://www.getvines.com/docs/
