### ISSUE TITLE
Document supported XEPs

### ISSUE THREAD

**Issue by jpcaruana** [negativecode/vines#19]
It is very hard to know which XEP are implemented, which aren't : one has to guess it from reading several pages on the website.
A page listing all implemented XEPs (Prosody does : this is good. see http://prosody.im/doc/xeplist) would be very useful. I don't think it would be useful to list unimplemented XEPs (Prosody does, this is bad)
Thanks

**Comment by jstdoit** [comment]
+1

**Comment by soyuka** [comment]
+1

And a doc to add XEP modules would be great !

**Comment by jstdoit** [comment]
Forget Vines!

**Comment by soyuka** [comment]
? gimme a better alternative :) (without it beeing written in C/Java/Erlang or Perl)
