### ISSUE TITLE
jRuby issue: FATAL -- vines: XMPP server stopped

### ISSUE THREAD

**Issue by ddrake** [negativecode/vines#26]
Hi, I did the simple Vines server install, and it worked fine with MRI on my Linux Mint 12 box.

But when I tried it with jRuby 1.7.4, the server starts correctly, but as soon as I log in one of the users (alice or arthur) in Pidgin, the server crashes with this message:

serial number must be a positive integer 
[2013-09-09T02:20:12Z] FATAL -- vines: XMPP server stopped

**Comment by Strech** [comment]
Please run vines with `log :debug` in `conf/config.rb` and attach trace to this issue

**Comment by dgraham** [comment]
EventMachine isn't fully implemented on jRuby, so it's, unfortunately, not supported.

**Comment by ddrake** [comment]
@dgraham - Thanks for the quick response!  The EventMachine readme says that JRuby is 'supported', but I see it has a number of open issues tagged 'jruby'.
@Strech - Sorry, I'm not able to attach a trace.  I changed to log :debug  as you suggested, but no additional information was dumped to the console.  If I start in daemon mode, no log file is created, a different message is written to the console: "Vines has started.  fork is not available on this platform" and the server stops immediately (i.e. before I even open Pidgin).
