### ISSUE TITLE
How to create account by code?

### ISSUE THREAD

**Issue by sharp** [negativecode/vines#33]
I want to create one xmpp account for my Rails User model

**Comment by dgraham** [comment]
You might look at the SQL schema the [vines-sql](https://github.com/negativecode/vines-sql) storage gem provides here:
https://github.com/negativecode/vines-sql/blob/master/lib/vines/storage/sql.rb#L154-L160

If your Rails app contains a `users` table with those same fields, both Vines and Rails can use the same table.
