### ISSUE TITLE
compliant with devise

### ISSUE THREAD

**Issue by skyeagle** [negativecode/vines#4]
It will be simpler to run any rails app as web interface instead js web if we will store authentication info compliant with devise defaults. What are you think about it?

**Comment by dgraham** [comment]
I haven't used devise, but it's easy to use custom authentication mechanisms in Vines.  The storage interface is designed to allow this type of customization.  You could subclass one of the existing Vines::Storage classes and override the authenticate method to use devise.

**Comment by skyeagle** [comment]
Ok, I will do it. Thanks for your job, it's really awesome.
