### ISSUE TITLE
Room persistance - (XEP-45)

### ISSUE THREAD

**Issue by sammcj** [negativecode/vines#46]
I couldn't see anything in the documentation around room persistence.
- XEP-45 implemented in Vines?
- If so, how do you configure it?

http://xmpp.org/extensions/xep-0045.html

**Comment by sammcj** [comment]
Oh wow it doesn't have MUC at all!

Blocking: https://github.com/negativecode/vines/issues/7

**Comment by dgraham** [comment]
A list of supported extensions is in the readme: https://github.com/negativecode/vines#standards-support.
