### ISSUE TITLE
MySQL key length issue

### ISSUE THREAD

**Issue by jesseadams** [negativecode/vines#6]
$ vines schema somedomain.com
-- create_table(:users, {:force=>false})
   -> 0.0160s
-- add_index(:users, :jid, {:unique=>true})
Schema creation failed: Mysql::Error: Specified key was too long; max key length is 767 bytes: CREATE UNIQUE INDEX `index_users_on_jid` ON `users` (`jid`)

**Comment by dgraham** [comment]
Fixed by commit https://github.com/negativecode/vines/commit/b8f0da50fe09b126a79b4e9975222d4e57399e20.  This fix will appear in the 0.4.0 release.
