### ISSUE TITLE
Implement MUC in Chat Server

### ISSUE THREAD

**Issue by jesseadams** [negativecode/vines#7]
Please consider implementing XEP-0045 in the Chat Server. http://xmpp.org/extensions/xep-0045.html

**Comment by soorajb** [comment]
+1

**Comment by elijh** [comment]
+1

**Comment by jhulick** [comment]
+1

**Comment by Telmo** [comment]
+1

**Comment by jpcaruana** [comment]
+1

**Comment by jbpotonnier** [comment]
+1

**Comment by vcarel** [comment]
+1 :-)

**Comment by elijh** [comment]
I will probably be starting work on this in the next six months, if anyone wants to join me.

**Comment by jessereynolds** [comment]
+1 :-)

**Comment by simonvc** [comment]
+1 I was really excited about vines, without MUC we'll be forced to go back to openfire or ejabberd or prosody :(

**Comment by lian** [comment]
+1

**Comment by sammcj** [comment]
+1

**Comment by jessereynolds** [comment]
A won't fix then? Good to have that sorted out.

**Comment by sammcj** [comment]
@jessereynolds sounds like a bit of a dead project to me - check out https://github.com/sdelements/lets-chat
Yes it's nodejs _shiver_ and mongodb _vomit_ but it does work really well, supports XMPP, OTR, MUC, Message archiving etc...

**Comment by jessereynolds** [comment]
@sammcj lets-chat looks good, thanks for that!

**Comment by AlanTupper** [comment]
While we're on the Node topic, there's also https://github.com/node-xmpp/node-xmpp-server

Edit: It doesn't seem to have quite the XEP support that lets-chat has however!
